#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "styling, testing, and linting your project code... before committing"

# Check Prettier
npm run check-format || 
(
    echo "Prettier check failed. Please run 'npm run format', add changes and try commit again.";
    false;
)

# Check ESLint
npm run check-lint || 
(
    echo "ESLint check failed. Make the reuired changes listed above and try commit again.";
    false;
)

# Check tsconfig
npm run check-types || 
(
    echo "Failed type check. Make the changes require above, add changes and try commit again.";
    false;
)

npm run build || 
(
    echo "Your build failed. View the error above";
    false;
)

echo "Success! All checks passed. Committing your changes..."